/** @type {import('typedoc').TypeDocOptions} */
export default {
  tsconfig: "tsconfig.docs.json",
  name: "SVG Fns",
  entryPoints: ["./packages/**/src"],
  exclude: ["**/*.test.*", "**/declaration.d.ts", "./packages/shared/**"],
  entryPointStrategy: "Expand",
  out: "./docs",
  commentStyle: "all",
  searchInComments: true,
  excludeExternals: true,
  plugin: [
    "typedoc-plugin-markdown",
    "typedoc-plugin-mdn-links",
    "typedoc-plugin-rename-defaults",
    "typedoc-plugin-missing-exports",
  ],
  hidePageHeader: true,
  sanitizeComments: true,
  router: "module",
  mergeReadme: true,
  hideBreadcrumbs: true,
  expandParameters: true,
  expandObjects: true,
  theme: "markdown",
};
