remote_theme: just-the-docs/just-the-docs
title: React18 Loaders
search_enabled: true
nav_sort: case_insensitive
footer_content: <p align="center" style="text-align:center">with 💖 by <a href="https://mayank-chaudhari.vercel.app" target="_blank">Mayank Kumar Chaudhari</a></p>
